name: CI - Push Release

on:
  push:
    branches:
      - develop
      - master
  workflow_dispatch:

env:
  DOCKER_HUB_USERNAME: mihajlovicka
  IMAGE_NAME: mihajlovicka/booking
  SERVICE_NAME: user-service

jobs:
  build-and-test-api:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Semantic Release
        id: release
        uses: cycjimmy/semantic-release-action@v4
        with:
          tag_format: ${{env.SERVICE_NAME}}-v${version}
          extra_plugins: |
            @semantic-release/commit-analyzer
            @semantic-release/release-notes-generator
            @semantic-release/github
            @semantic-release/git
            @semantic-release/exec
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_API_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build Final Docker Image Using Cache and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          target: final
          cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:${{env.SERVICE_NAME}}-buildcache
          cache-to: type=registry,ref=${{ env.IMAGE_NAME }}:${{env.SERVICE_NAME}}-buildcache,mode=max
          tags: ${{ env.IMAGE_NAME }}:${{env.SERVICE_NAME}}-${{ steps.release.outputs.new_release_version }}
          push: true
